# Generated by Django 6.1 on 2026-09-11 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_delete_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='is_ongoing',
        ),
    ]
